[package]
name = "bevy_ios_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "bevy_ios_example"
crate-type = ["staticlib"]

[dependencies]
endless_pinball = {path = "../../" }